# Site settings
title: Georgy Blog
email: petukhovg@gmail.com
description: > 
  Blog about technology and other fun stuff that interests Georgy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://g-petukhov.com" # the base hostname & protocol for your site
github_username:  petukhov

# Build settings
markdown: kramdown

